version: 2.1
orbs:
  node: circleci/node@5.1.0
  cypress: cypress-io/cypress@3.1.3

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run build
          command: npm run build
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  start_server:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Start server
          command: npm run start:dev


workflows:
  test_my_app:
    jobs:
      - start_server
      - cypress/run: 
          cypress-command: npx cypress run --browser electron
          requires:
            - start_server