version: 2.1
orbs:
  node: circleci/node@5.1.0
  cypress: cypress-io/cypress@3.1.3

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run build
          command: npm run build
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  run_server:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Start local server
          command: npm run start:dev
          background: true

workflows:
  version: 2
  test_my_app:
    jobs:
      - run_server
      - cypress/run:
          requires:
            - run_server
          cypress-command: npx cypress run --browser electron --config baseUrl=http://localhost:3000
      - build:
          requires:
            - cypress/run